logger:
  default: info
  logs:
    custom_components.epb: debug
    custom_components.epb.api: debug
    custom_components.epb.coordinator: debug
    custom_components.epb.sensor: debug
    aiohttp.client: debug  # This will show us the actual HTTP requests 