---
    name: Code Quality
    
    on:
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]
    
    jobs:
      quality:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: "3.9"
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements-dev.txt
          - name: Format code
            run: |
              black . --diff
              black .
          - name: Run linters
            run: |
              flake8 .
              isort . --check-only --diff
          - name: Type check
            run: |
              mypy .