---
    name: Code Quality

    on:
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]

    jobs:
      format:
        name: Format code
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - uses: actions/checkout@v4
            with:
              ref: ${{ github.head_ref }}
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: "3.11"
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements_dev.txt
          - name: Format code
            run: |
              black .
              isort .
          - name: Commit changes
            run: |
              git config --global user.name 'github-actions'
              git config --global user.email 'github-actions@github.com'
              git add .
              git diff --quiet && git diff --staged --quiet || (git commit -m 'style: format code with black and isort' && git push)

      lint:
        needs: format
        name: Check code quality
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: "3.11"
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements_dev.txt
          - name: Run linters
            run: |
              flake8 .
          - name: Type check
            run: |
              mypy .
