---
name: "Release"

on:
  release:
    types: [published]

permissions:
  contents: write
  
jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate with hassfest
        uses: home-assistant/actions/hassfest@master

      - name: Validate with HACS
        uses: hacs/action@main
        with:
          category: integration

      - name: ZIP integration directory
        run: |
          cd custom_components/epb
          zip epb.zip -r ./

      - name: Upload zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: custom_components/epb/epb.zip
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
