---
    name: "Validate"
    
    on:
      push:
        branches:
          - main
          - dev
      pull_request:
      schedule:
        - cron: "0 0 * * *"
    
    jobs:
      validate:
        runs-on: "ubuntu-latest"
        steps:
          - uses: "actions/checkout@v4"
          
          - name: HACS validation
            uses: "hacs/action@main"
            with:
              category: "integration"
              
          - name: Hassfest validation
            uses: "home-assistant/actions/hassfest@master"
    
      style:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: "3.11"
              cache: "pip"
          
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install ruff black mypy
              pip install -r requirements-dev.txt
          
          - name: Run black
            run: black . --check
            
          - name: Run ruff
            run: ruff check .
            
          - name: Run mypy
            run: mypy custom_components/epb
    
      tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: "3.11"
              cache: "pip"
              
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements-dev.txt
              
          - name: Run tests
            run: |
              pytest \
                --cov=custom_components/epb \
                --cov-report=xml \
                -v \
                tests/
                
          - name: Upload coverage to Codecov
            uses: codecov/codecov-action@v4
            with:
              token: ${{ secrets.CODECOV_TOKEN }}
              file: ./coverage.xml
              flags: unittests