---
    name: "Validate"

    on:
      push:
        branches:
          - main
          - dev
      pull_request:
      schedule:
        - cron: "0 0 * * *"

    jobs:
      validate:
        runs-on: "ubuntu-latest"
        steps:
          - uses: "actions/checkout@v4"

          - name: Set up Python
            uses: "actions/setup-python@v5"
            with:
              python-version: "3.11"

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -e ".[test]"
              pip install -r requirements_dev.txt

          - name: Validate with hassfest
            uses: "home-assistant/actions/hassfest@master"

          - name: Validate with HACS
            uses: "hacs/action@main"
            with:
              category: "integration"

      style:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: "3.11"

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -e ".[test]"
              pip install -r requirements_dev.txt

          - name: Check code formatting
            run: |
              black .
              isort .

          - name: Lint with flake8
            run: flake8 .

          - name: Type check with mypy
            run: |
              mypy custom_components/epb/ tests/

      tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: "3.11"

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -e ".[test]"
              pip install -r requirements_dev.txt

          - name: Run tests
            run: |
              pytest

          - name: Upload coverage to Codecov
            uses: codecov/codecov-action@v4
            with:
              file: ./coverage.xml
              flags: unittests
